# Pandas

In [91]:
#importamos librerias
import pandas as pd
import os
from pathlib import Path

In [92]:
# cargamos la data en un DF

root=Path(".").resolve()
filename="apple_quality.csv"
pathdata=os.path.join(root,'data','raw',filename)

#Leemos el archivo
df=pd.read_csv(pathdata)
df.head()

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good

In [93]:
df['Quality'][2]

'bad'

In [94]:
df.iloc[0]

A_id                    0.0
Size              -3.970049
Weight            -2.512336
Sweetness           5.34633
Crunchiness       -1.012009
Juiciness            1.8449
Ripeness            0.32984
Acidity        -0.491590483
Quality                good
Name: 0, dtype: object

In [95]:
df.iloc[:,0]

0          0.0
1          1.0
2          2.0
3          3.0
4          4.0
         ...
3996    3996.0
3997    3997.0
3998    3998.0
3999    3999.0
4000       NaN
Name: A_id, Length: 4001, dtype: float64

In [96]:
df.iloc[:3,0]

0    0.0
1    1.0
2    2.0
Name: A_id, dtype: float64

In [97]:
df.iloc[[1,200,4000],0]

1         1.0
200     200.0
4000      NaN
Name: A_id, dtype: float64

In [98]:
df.iloc[:,:-5]

        A_id      Size    Weight  Sweetness
0        0.0 -3.970049 -2.512336   5.346330
1        1.0 -1.195217 -2.839257   3.664059
2        2.0 -0.292024 -1.351282  -1.738429
3        3.0 -0.657196 -2.271627   1.324874
4        4.0  1.364217 -1.296612  -0.384658
...      ...       ...       ...        ...
3996  3996.0 -0.293118  1.949253  -0.204020
3997  3997.0 -2.634515 -2.138247  -2.440461
3998  3998.0 -4.008004 -1.779337   2.366397
3999  3999.0  0.278540 -1.715505   0.121217
4000     NaN       NaN       NaN        NaN

[4001 rows x 4 columns]

In [99]:
df.loc[0,'Quality']

'good'

In [100]:
df.loc[:,['Quality','Size','Weight']]

     Quality      Size    Weight
0       good -3.970049 -2.512336
1       good -1.195217 -2.839257
2        bad -0.292024 -1.351282
3       good -0.657196 -2.271627
4       good  1.364217 -1.296612
...      ...       ...       ...
3996    good -0.293118  1.949253
3997     bad -2.634515 -2.138247
3998    good -4.008004 -1.779337
3999    good  0.278540 -1.715505
4000     NaN       NaN       NaN

[4001 rows x 3 columns]

In [101]:
df.Quality == 'good'

0        True
1        True
2       False
3        True
4        True
        ...
3996     True
3997    False
3998     True
3999     True
4000    False
Name: Quality, Length: 4001, dtype: bool

In [102]:
df.loc[df.Quality == 'bad']

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
5,5.0,-3.425400,-1.409082,-1.913511,-0.555775,-3.853071,1.914616,-2.981523169,bad
8,8.0,-3.867632,-3.734514,0.986429,-1.207655,2.292873,4.080921,-4.871904758,bad
9,9.0,-0.727983,-0.442820,-4.092223,0.597513,0.393714,1.620857,2.185607723,bad
10,10.0,-2.699336,-1.329507,-1.418507,-0.625546,2.371074,3.403165,-2.810808169,bad
...,...,...,...,...,...,...,...,...,...
3989,3989.0,-2.282625,-0.225517,-1.698524,0.936855,-1.385481,3.249894,1.047021307,bad
3990,3990.0,-1.396794,-0.599596,-1.931104,1.815668,1.670732,1.614027,-0.987967575,bad
3993,3993.0,1.520142,-0.352623,-3.206467,1.341719,0.675568,0.107093,-0.945080106,bad
3995,3995.0,0.059386,-1.067408,-3.714549,0.473052,1.697986,2.244055,0.137784369,bad
3997,3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad

In [103]:
df.loc[(df['Quality']=='bad')& (df.Size >4)]

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
1301,1301.0,4.123222,-1.651736,-0.554216,3.838873,-3.748403,-3.931116,-0.33283833,bad
2262,2262.0,4.102549,-1.532028,1.739175,3.508420,-3.581638,-3.467742,1.811772403,bad
3494,3494.0,4.649923,-1.675508,-3.241841,5.333283,-4.830750,-3.811951,-0.518724707,bad
3957,3957.0,4.086332,0.601599,0.934812,5.780529,-2.627074,-4.676170,4.689126107,bad

In [104]:
df.loc[df['A_id'].isin([400])]

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
400,400.0,-1.455035,-0.094437,-1.810407,0.631184,2.116622,-2.282722,-1.590347457,good

In [105]:
df.loc[df.Quality.notnull()]

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good
...,...,...,...,...,...,...,...,...,...
3995,3995.0,0.059386,-1.067408,-3.714549,0.473052,1.697986,2.244055,0.137784369,bad
3996,3996.0,-0.293118,1.949253,-0.204020,-0.640196,0.024523,-1.087900,1.854235285,good
3997,3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad
3998,3998.0,-4.008004,-1.779337,2.366397,-0.200329,2.161435,0.214488,-2.229719806,good
3999,3999.0,0.278540,-1.715505,0.121217,-1.154075,1.266677,-0.776571,1.599796456,good

In [106]:
df.loc[df.Quality.isna()]

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
4000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Created_by_Nidula_Elgiriyewithana,NaN

In [107]:
df.loc[df.Quality == 'good',['Quality']]='Bueno'
df.head()

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,Bueno
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,Bueno
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,Bueno
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,Bueno

In [126]:
df['rankr']=range(0,len(df),1)
df

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality,rankr
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,Bueno,0
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,Bueno,1
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad,2
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,Bueno,3
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,Bueno,4
...,...,...,...,...,...,...,...,...,...,...
3996,3996.0,-0.293118,1.949253,-0.204020,-0.640196,0.024523,-1.087900,1.854235285,Bueno,3996
3997,3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad,3997
3998,3998.0,-4.008004,-1.779337,2.366397,-0.200329,2.161435,0.214488,-2.229719806,Bueno,3998
3999,3999.0,0.278540,-1.715505,0.121217,-1.154075,1.266677,-0.776571,1.599796456,Bueno,3999
4000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Created_by_Nidula_Elgiriyewithana,NaN,4000

In [125]:
help('range')

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |
 |  Methods defined here:
 |
 |  __bool__(self, /)
 |      True if self else False
 |
 |  __contains__(self, key, /)
 |      Return key in self.
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __len__(self, /)
 |      Return len(self).
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __reduce__(...)
 |      Helper for pickle.
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __reversed__(...)
 |      Return a reverse iterator.
 |
 |  count(...)
 |      rangeobject.count(value) -> integer -- return number of occurrences of value
 |
 |  index(...)
 |      rangeobject.index(value) -> integer -- return index of value.
 |      Raise ValueError if the value is not present.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  start
 |
 |  step
 |
 |  stop